config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'resume', to: 'pages#resume'
  get 'blue', to: 'pages#blue'
  get 'white', to: 'pages#white'
  get 'red', to: 'pages#red'
  get 'veronique', to: 'pages#veronique'
  get 'belmondo', to: 'pages#belmondo'
  get 'cyanure', to: 'pages#cyanure'
  get 'marie', to: 'pages#marie'
  get 'central', to: 'pages#central'
  get 'soil', to: 'pages#soil'
  get 'tout', to: 'pages#tout'
  resources :projects, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def resume
  end

  def blue
  end

  def white
  end

  def red
  end

  def veronique
  end

  def belmondo
  end

  def cyanure
  end

  def marie
  end

  def central
  end

  def soil
  end

  def tout
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Urszula Lesiak Website</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Julius+Sans+One|Lato:300,400,700" rel="stylesheet">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <% unless action_name == "home" %>
    <%= render "shared/navbar"%>
    <% end %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-layout">
  <div class="parallax">
    <div class="parallax-content text-center">
      <h2>ABOUT ME</h2>
      <p>FILM EDITOR</p>
    </div>
  </div>
</div>
<div class="about-content">
  <div class="about-txt about-flex-item">
    <div class="row">
      <div class="col-xs-12 col-sm-6 txt-left">
        <p><span class="first-letter">L</span>orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
      <div class="col-xs-12 col-sm-6">
        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>
      </div>
    </div>
  </div>
</div>
<div class="parallax-2">
</div>
<div class="about-footer text-center">
  <div class="row">
    <a href="javascript:" class="floating scroll-center text-center" id="return-to-top">
      <i class="fa fa-angle-up" aria-hidden="true"></i>
      <p id="scroll-text">BACK TO TOP</p>
    </a>
  </div>
</div>
<

<%= content_for(:after_js) do %>
  <%= javascript_tag do %>
    $('#return-to-top').click(function() {
    // When arrow is clicked
      $('body,html').animate({
          scrollTop : 0
      // Scroll to top of body
      }, 500);
    });
  <% end %>
<% end %>

app/views/pages/belmondo.html.erb
<section id="films">
  <div class="video">
    <iframe width="710" height="420" src="https://www.youtube.com/embed/MgToPZuRMi0?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
  </div>
  <div class="content-film">
    <h1>Belmondo par Belmondo</h1>
    <h2>Régis Mardon</h2>
    <p> documentary, TF1</p>
  </div>
</section>

app/views/pages/blue.html.erb
<section id="films">
  <div class="video">
    <iframe width="710" height="420" src="https://www.youtube.com/embed/Hxu6my_t4pM?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
  </div>
  <div class="content-film">
    <h1>Blue</h1>
    <h2>Krzysztof Kieślowski</h2>
    <p>The first part of Kieslowski's trilogy on France's national motto: Liberty, Equality, and Fraternity.</p>
  </div>
</section>

app/views/pages/contact.html.erb
<div class="wrapper-contact">
  <div class="parent-contact-left">
      <div class="child-left-contact" style='background-image: linear-gradient(rgba(255,255,255,0.1),rgba(255,255,255,0.2)), url(<%= image_path 'phone.jpg' %>)'>
      </div>
  </div>
  <div class="parent-contact-right">
    <div class="child-right-contact">
      <div class="container-contact">
        <form id="contact" action="https://formspree.io/zuzglowacka@gmail.com" method="POST">
          <h3>Contact me</h3>
          <fieldset>
            <input placeholder="Your name (required)" type="text" name="name" tabindex="1" required autofocus>
          </fieldset>
          <fieldset>
            <input placeholder="Your Email Address (required)" type="email" name="_replyto" tabindex="2" required>
          </fieldset>
          <fieldset>
            <input placeholder="Your Phone Number" type="tel" name="phone_number" tabindex="3">
          </fieldset>
          <fieldset>
            <input placeholder="Your Web Site starts with http://" type="url" name="website" tabindex="4">
          </fieldset>
          <fieldset>
            <textarea placeholder="Type your Message Here..." name="message" tabindex="5" required></textarea>
          </fieldset>
          <fieldset>
            <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Send</button>
          </fieldset>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/pages/cyanure.html.erb
<section id="films">
  <div class="video">
    <iframe width="710" height="420" src="https://www.youtube.com/embed/MKUtCJwjnZw?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
  </div>
  <div class="content-film">
    <h1>Cyanide (Cyanure)</h1>
    <h2>Séverine Cornamusaz</h2>
    <p>A young hopeful teenager is waiting for his unknown and fantasized father to come out of prison. His family dream life is seriously undermined by an exhausted mother and a man who, after so many years in jail, has become unable to be a responsible father.</p>
  </div>
</section>

app/views/pages/home.html.erb
<div class="wrapper">
  <div class="parent">
    <%= link_to about_path do %>
      <div class="child left" style='background-image: linear-gradient(rgba(255,255,255,0.1),rgba(255,255,255,0.2)), url(<%= image_path 'realization.jpg' %>)'>
    </div>
    <h1 class="caption">View my website</h1>
    <% end %>
  </div>

  <div class="parent">
    <%= link_to resume_path do %>
      <div class="child right" style='background-image: linear-gradient(rgba(255,255,255,0.3), rgba(255,255,255,0.2)), url(<%= image_path 'camera.jpg' %>)'>
      </div>
      <h1 class="caption">View my resumé</h1>
    <% end %>
  </div>
</div>

app/views/pages/marie.html.erb
<section id="films">
  <div class="video">
    <iframe width="710" height="420" src="https://www.youtube.com/embed/BqY-l-YF2UA?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
  </div>
  <div class="content-film">
    <h1>In the Footsteps of Marie Curie</h1>
    <h2>Krzysztof Rogulski</h2>
    <p>The film tells of the principal stages in Marie Curie's life and career. She was a citizen of Warsaw, famous scientist- double winner of Nobel prize in Science. Our interlocutors they are e.g. L'Oreal-Unesco prize winner "Women in Science" from 2011. There are women-scientists from five continents. All are awarded of the prize amounted of 100 000 dollars for scientific works of the greatest meaning to the humanity.</p>
  </div>
</section>

app/views/pages/red.html.erb
<section id="films">
  <div class="video">
    <iframe width="710" height="420" src="https://www.youtube.com/embed/RPLpbDFQZpg?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
  </div>
  <div class="content-film">
    <h1>Red</h1>
    <h2>Krzysztof Kieślowski</h2>
    <p>Krzysztof Kieślowski closes his Three Colors trilogy in grand fashion, with an incandescent meditation on fate and chance, starring Irène Jacob as a sweet-souled yet somber runway model in Geneva whose life dramatically intersects with that of a bitter retired judge, played by Jean‑Louis Trintignant.</p>
  </div>
</section>

app/views/pages/resume.html.erb
<div class="about-layout">
  <div class="parallax-4">
    <div class="parallax-content text-center">
      <h2>MY RESUMÉ</h2>
    </div>
  </div>
  <div class="entry-content">
    <h1>
      Urszula Lesiak
      <br>
      Feature film and documentary editor/<br>
      Documentary film co-director and co-author/<br>
      Script doctor/<br>
      Editing doctor
    </h1>
    <p>
      Chief editor in feature and documentary films directed by Krzysztof Kieslowski, Jörg Helbling, Andrzej Wajda, Olias Barco, Atiq Rahimi, Greg Zglinski.<br>
      Gained a broad international experience in the industry and took part in the creation of almost 60 feature and documentary films.
    </p>
    <p>
      Script analysis before shooting
    </p>
    <p>
      Editing doctor - final cut, worked with Severine Cornamuzas, Greg Zglinski , Kamal Musale, Olga Chajdas, in collaboration with Cab Productions, Louise Productions, tellfilm gmbh-Katrin Renz, FILM IT, SCORPIO Productions etc.
    </p>
    <p>
      Scenario co-writer for feature-documentary projects
    <p>
      Documentaries co-director (collaboration with Hanna Polak, Piotr Jaxa and Manon Loizeau)
    <p>
      Chief editor in almost 20 theatrical cinema trailers
    </p>
    <p>
      Assistant editor in feature films directed by Maurice Pialat, Gerard Oury, Lars von Trier and Emir Kusturica
    </p>
    <h1>
      Selected filmography
    </h1>
    <p>
      <strong>2015/16</strong> BELMONDO PAR BELMONDO, documentary, TF1, editor and co-author<br>
      <strong>2013</strong> LES REINES DE SABA, documentary, AMIP PROD; France, dir. by MANON LOIZEA, Chief Editor<br>
      <strong>2012</strong> CYANURE, feature film, PS PRODUCTION, SWITZERLAND, dir. By S. CORNAMUZAS, Chief Editor<br>
      <strong>2011</strong> MARIE CURIE SKLODOWSKA, documentary, ALCHIMIC PROD, France, Author and Chief Editor<br>
      <strong>2009</strong> LA FRANCE DES CAMPS, documentary, dir. by J. Amat, PHARES ET BALISES, France 2, Chief Editor<br>
      <strong>2008</strong> CENTRAL NUIT, SEASON 7, SERIAL TV, 6 episodes, dir. by Félix Olivier, France 2, Chief Editor<br>
      <strong>2008</strong> MARECHAL, NOUS VOILA?, documentary, dir. by J. Amat, PHARES ET BALISES, France 2, Chief Editor<br>
      <strong>2007</strong> PARTIR A TOUT PRIX, documentary, dir. by A. Camacho, AGAT FILMS, FR 3, Chief Editor<br>
      <strong>2006</strong> LE SOLEIL ORANGE (THE ORANGE SUN), dir. by Piotr Jaxa, Hanna Polak and Urszula Lesiak, documentary, Green Light & HesseGreutert, Switzerland, Chief Editor & Co-Director<br>
      <strong>2004</strong> TOUT UN HIVER SANS FEU, dir. by Greg Zglinski, feature, CAB, Switzerland, Chief Editor<br>
      <strong>2004</strong> TERRE ET CENDRE (SOIL AND ASHES), dir. by Atiq Rahimi, feature, Les Films du Lendemains, France, Chief Editor<br>
      <strong>2003</strong> NORD-OST, dir. by M. Loiseaux and Urszula Lesiak, documentary, ARTE, France, Chief Editor & Co-Director<br>
      <strong>2003</strong> SNOWBOARDER, dir. by Olias Barco, feature, NORD-EST Productions, France/Switzerland, Chief Editor<br>
      <strong>1999</strong> PAN TADEUSZ, dir. by Andrzej Wajda, feature, international version, Films de Lausanne, Poland/France, Chief Editor<br>
      <strong>1997</strong> LE NAIN ROUGE, dir. by Ivan le Moine, AAA Fillm Belges<br>
      <strong>1995</strong> DER NEBELLÄUFER, dir. by Jörg Helbling, Edi Hubschmid Produktion AG, Switzerland, Chief Editor<br>
      <strong>1994</strong> BLANC (WHITE), dir. by Krzysztof Kieslowski, feature, MK 2, France/Poland/Switzerland, Chief Editor<br>
      <strong>1994</strong> ROUGE (RED), dir. by Krzysztof Kieslowski, feature, MK 2, France/Poland/Switzerland, Assistant Editor Interpreter<br>
      <strong>1993</strong> BLEU (BLUE), dir. by Krzysztof Kieslowski, feature, MK 2, France/Poland/Switzerland, Assistant Editor Interpreter<br>
      <strong>1993</strong> ARIZONA DREAM, dir. by Emir Kusturica, feature, Constellation Productions, USA/France, Assistant Editor<br>
      <strong>1991</strong> EUROPA, dir. by Lars von Trier, feature, Gérard Mital Productions, Denmark/France, Assistant Editor<br>
      <strong>1991</strong> LA DOUBLE VIE DE VERONIQUE (THE DOUBLE LIFE OF VERONIQUE), dir. by Krzysztof Kieslowski, feature, Sideral, France/Poland,      Assistant Editor<br>
      <strong>1989</strong> VANILLE–FRAISE, dir. by Gérard Oury, feature, Ariane Films, France, Assistant Editor<br>
      <strong>1985</strong> POLICE, dir. by Maurice Pialat, feature, Gaumont, France, Assistant Editor<br>
    </p>
    <h1>
      Selected theatrical trailers (concept and editing)
    </h1>
    <p>
      LE CERCLE (THE CIRCLE), dir. by Jafar Panahi (Iran)<br>
      DJOMEH, dir. by Hassan Yektapanah (Iran)<br>
      LA FAUTE A VOLTAIRE (BLAME IT ON VOLTAIRE), dir. by  Abdellatif Kechiche (France)<br>
      PLEURE PAS GERMAINE (DON'T CRY, GERMAINE), dir. by Alain de Halleux (Belgium)<br>
      LA VIE EXTRAORDINAIRE DE DONA FLORES, dir. by A. Waddingtone (Brazil)<br>
      LIBERTAD (FREEDOM), dir. by Lisandro Alonso (Argentina)
      SUSPICIOUS RIVER, dir. by Lynne Stopkewitch (Canada)<br>
      TIERE, dir. by Greg Zglinski (Switzerland)<br>
    </p>
    <h1>
      Additional Experience
    </h1>
    <p>
      <strong>2009, 2011, 2014</strong> Film editing lecturer, The American University of Paris<br>
       <strong>2011</strong> Film editing lecturer and editing supervisor at Head-Haute Ecole D'Art et Design Geneve, Switzerland<br>
      <strong>2010</strong> Member of jury at Head-Haute Ecole D'Art et Design Geneve, Switzerland<br>
    </p>





















  </div>
</div>

app/views/pages/soil.html.erb
<section id="films">
  <div class="video">
    <iframe width="710" height="420" src="https://www.youtube.com/embed/yj0TMBA3S3g?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
  </div>
  <div class="content-film">
    <h1>Earth and Ashes (Terre et Cendres)</h1>
    <h2>Atiq Rahimi</h2>
    <p> Elderly Dastaguir and his newly deaf 5-year-old grandson Yassin hitchhike and walk, but mostly walk, as they make their way to the coal mine where Dastaguir's son Murad works. Dastaguir must tell Murad that the rest of their family were all killed in a recent bomb attack.</p>
  </div>
</section>

app/views/pages/veronique.html.erb
<section id="films">
  <div class="video">
    <iframe width="710" height="420" src="https://www.youtube.com/embed/iBrPfR6oMsM?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
  </div>
  <div class="content-film">
    <h1>The Double Life of Veronique</h1>
    <h2>Krzysztof Kieślowski</h2>
    <p>Nominated for 1 Golden Globe.</p>
  </div>
</section>

app/views/pages/white.html.erb
<section id="films">
  <div class="video">
    <iframe width="710" height="420" src="https://www.youtube.com/embed/xECEAPfdqic?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
  </div>
  <div class="content-film">
    <h1>White</h1>
    <h2>Krzysztof Kieślowski</h2>
    <p>White is the second part of Krzysztof Kieslowski's trilogy based on the colours of the French flag and upon the precepts of liberty, freedom and equality</p>
  </div>
</section>

app/views/projects/index.html.erb
<div class="about-layout">
  <div class="parallax-3">
    <div class="parallax-content text-center">
      <h2>MY EDITING WORK</h2>
    </div>
  </div>
  <div id="wrapper">
    <div class="container">
      <div class="cards">
        <div class="courses-box">
          <%= link_to belmondo_path do %>
            <div class="card" style="background-image: url('http://res.cloudinary.com/zuziac/image/upload/v1530736863/belmondo.jpg');">
            </div>
          <% end %>
          <div class="card-course-name">
            <h3>Belmondo par Belmondo</h3>
          </div>
        </div>
        <div class="courses-box">
          <%= link_to cyanure_path do %>
            <div class="card" style="background-image: url('http://res.cloudinary.com/zuziac/image/upload/v1530738190/cyanure.jpg');">
            </div>
          <% end %>
          <div class="card-course-name">
            <h3>Cyanide</h3>
          </div>
        </div>
        <div class="courses-box">
          <%= link_to marie_path do %>
            <div class="card" style="background-image: url('http://res.cloudinary.com/zuziac/image/upload/v1530794364/marie.jpg');">
            </div>
          <% end %>
          <div class="card-course-name">
            <h3>In the Footsteps of Marie Curie</h3>
          </div>
        </div>
        <div class="courses-box">
          <div class="card" style="background-image: url('http://res.cloudinary.com/zuziac/image/upload/v1530795114/central-nuit.jpg');">
          </div>
          <div class="card-course-name">
            <h3>Central Nuit</h3>
          </div>
        </div>
        <div class="courses-box">
          <%= link_to soil_path do %>
            <div class="card" style="background-image: url('http://res.cloudinary.com/zuziac/image/upload/v1530795676/soil.jpg');">
            </div>
          <% end %>
          <div class="card-course-name">
            <h3>Earth and Ashes</h3>
          </div>
        </div>
        <div class="courses-box">
          <div class="card" style="background-image: url('http://res.cloudinary.com/zuziac/image/upload/v1530796560/tout.jpg');">
          </div>
          <div class="card-course-name">
            <h3>Tout un hiver sans feu</h3>
          </div>
        </div>
        <div class="courses-box">
          <%= link_to veronique_path do %>
            <div class="card" style="background-image: url('http://res.cloudinary.com/zuziac/image/upload/v1526671411/MV5BOGYyNDE1YTMtMTg5Mi00NzI2LTg1OWQtNzI1YTYzM2JiNmQ3XkEyXkFqcGdeQXVyNzQ0MTcyMjU_._V1_SY1000_CR0_0_706_1000_AL_.jpg');">
          </div>
          <% end %>
          <div class="card-course-name">
            <h3>The Double Life of Veronique</h3>
          </div>
        </div>
        <div class="courses-box">
          <%= link_to blue_path do %>
            <div class="card" style="background-image: url('http://res.cloudinary.com/zuziac/image/upload/v1525788470/MV5BZGJhNDdmMWMtNzZiYy00MmFiLThjNmUtYTE1ZjRkNjdjYmQ5XkEyXkFqcGdeQXVyMTMxODk2OTU_._V1_.jpg');">
            </div>
          <% end %>
          <div class="card-course-name">
            <h3>Blue</h3>
          </div>
        </div>
        <div class="courses-box">
          <%= link_to white_path do %>
            <div class="card" style="background-image: url('http://res.cloudinary.com/zuziac/image/upload/v1525451411/MV5BMTU2NjY3NDAwMF5BMl5BanBnXkFtZTcwOTc4OTcxMQ_._V1_.jpg');">
            </div>
          <% end %>
          <div class="card-course-name">
            <h3>White</h3>
          </div>
        </div>
        <div class="courses-box">
          <%= link_to red_path do %>
            <div class="card" style="background-image: url('http://res.cloudinary.com/zuziac/image/upload/v1525987606/MV5BMTMzNjQ1Mjc0M15BMl5BanBnXkFtZTcwNDA0NjkxMQ_._V1_.jpg');">
            </div>
          <% end %>
          <div class="card-course-name">
            <h3>Red</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag('logo1.png') %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to about_path, class: 'navbar-wagon-item nav-link hvr-underline-from-center' do %>
      <p>ABOUT ME</p>
      <% end %>
    <%= link_to projects_path, class: 'navbar-wagon-item nav-link hvr-underline-from-center' do %>
      <p>PROJECTS</p>
    <% end %>
    <%= link_to contact_path, class: 'navbar-wagon-item nav-link hvr-underline-from-center' do %>
      <p>CONTACT</p>
    <% end %>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <!-- <div class="dropdown">
        <%# image_tag 'avatar.png', class: 'avatar dropdown-toggle', id: 'navbar-wagon-menu', data: {toggle: 'dropdown'} %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#"><i class="fa fa-info-circle" aria-hidden="true"></i> About</a></li>
          <li><a href="#"><i class="fa fa-picture-o" aria-hidden="true"></i> Projects</a></li>
        </ul>
      </div> -->
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to about_path, class: 'navbar-wagon-item nav-link' do %>
            <i class="fa fa-info-circle" aria-hidden="true"></i> About
          <% end %>
        </li>
        <li>
          <%= link_to projects_path, class: 'navbar-wagon-item nav-link' do %>
            <i class="fa fa-picture-o" aria-hidden="true"></i> Projects
          <% end %>
        </li>
        <li>
          <%= link_to contact_path, class: 'navbar-wagon-item nav-link' do %>
            <i class="fa fa-picture-o" aria-hidden="true"></i> Contact
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>